<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>SignalScheduler</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SignalScheduler.Shared\SignalScheduler.Shared.csproj" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
  </ItemGroup>
</Project>
