<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>SignalScheduler.Service</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SignalScheduler.Shared\SignalScheduler.Shared.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.1" />
  </ItemGroup>
</Project>
